# Generated by Django 5.0.1 on 2024-02-01 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0006_alter_sector_managers_sector_level_sector_lft_and_more",
        ),
        ("governanceplatform", "0007_sector_creator_sector_creator_name"),
    ]

    operations = []
