# Generated by Django 5.0.1 on 2024-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0008_merge_20240201_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulator",
            name="email_for_notification",
            field=models.EmailField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                verbose_name="email address for incident notification",
            ),
        ),
    ]
