# Generated by Django 5.0.2 on 2024-02-13 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0009_alter_regulator_email_for_notification"),
        (
            "governanceplatform",
            "0009_remove_companyuser_company_remove_companyuser_user_and_more",
        ),
    ]

    operations = []
