# Generated by Django 4.2 on 2024-02-23 12:49

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "governanceplatform",
            "0010_cert_certuser_user_certs_certuser_unique_certuser",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatorTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("full_name", models.TextField(blank=True, default="", null=True)),
                ("description", models.TextField(blank=True, default="", null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="governanceplatform.regulator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regulator Translation",
                "db_table": "governanceplatform_regulator_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
