# Generated by Django 4.2 on 2024-02-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governanceplatform', '0012_migrate_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulator',
            name='description',
        ),
        migrations.RemoveField(
            model_name='regulator',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='regulator',
            name='name',
        ),
    ]
