# Generated by Django 5.0.1 on 2024-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0022_impact_creator_impact_creator_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="impact",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="impact",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="impact",
            name="rght",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="impact",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
